image: Visual Studio 2017
build: off

clone_folder: c:\gopath\src\github.com\gomods\athens

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org
  SKIP_UNTIL_113: true
  ATHENS_USE_TEST_CONTAINERS: 1

stack: go 1.13

test_script:
  - go test -v ./...
